apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "suwayomi.fullname" . }}
  labels:
    {{- include "suwayomi.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "suwayomi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "suwayomi.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "suwayomi.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{ if or (.Values.server) (eq .Values.existingConfig.enabled true) -}}
      initContainers: 
        - name: copy-config
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: busybox:1.28
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{ if or (.Values.server) (.Values.existingConfig) (.Values.volumeMounts) -}}
          command: [sh,-c,'timeout -s TERM 2 java -Duser.home=/home/suwayomi -jar "/home/suwayomi/startup/tachidesk_latest.jar"; cat /overwrite/server.conf | while IFS= read -r line; do echo "Parsing line: $line"; sed -i "/$(echo -n "$line" | cut -d"=" -f1 | sed -e "s/^ *//" -e "s/ *$//")/c\\$line" /home/suwayomi/.local/share/Tachidesk/server.conf; done']
          volumeMounts:
          {{- end}}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
            - name: config
              mountPath: /overwrite
              readOnly: true
            - name: data
              mountPath: /home/suwayomi/.local/share/Tachidesk
      {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.env}}
          env:
            {{- toYaml . | nindent 12}}
          {{- end}}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /home/suwayomi/.local/share/Tachidesk/
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if .Values.server }}
        - name: config
          configMap:
            name: {{ include "suwayomi.fullname" . }}-config
        {{- else if eq .Values.existingConfig.enabled true -}}
        - name: config
          configMap:
            name: {{ .Values.existingConfig.configName }}
            items:
              - key: {{ .Values.existingConfig.configKey}}
                path: "server.conf"
        {{- end }}
        - name: data
        {{- if eq .Values.persistence.enabled true}}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "suwayomi.fullname" .) }}
        {{- else}}
          emptyDir: {}
        {{- end}}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
